project:
  type: book
  output-dir: docs


book:
  title: "Transporte en nanoestructuras de Bi"
  author: "Montserrat Navarro Espino"
  date: "7/31/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - geommetry.qmd
    - hamiltonian.qmd
    - transp.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



